### ISSUE TITLE
Cached partial for header.html breaks language drop down

### ISSUE THREAD

**Issue by christxph** [themefisher/bigspring-light#50]
The language drop-down always contains the current URL and the corresponding URLs for other languages. This means that `header.html` needs to be rebuilt for every page. This works fine during development but in production builds `partialCached` is used, which means that header.html gets built once and then used on all pages which causes the drop-down to point to the same URL on all pages.

So L27:
https://github.com/themefisher/bigspring-light/blob/2ac514278034bedfb863f8d4073308f5be65bcdd/layouts/_default/baseof.html#L25-L31

should be changed to:
```
{{ partial "header.html" . }}
```

**Comment by somratpro** [comment]
Hello @christxph,

Thanks for your concern. I already fixed this issue. You can download the latest code for a better experience. 

Did you know, we have a premium version of the Bigspring, which has a lot of premium features. You can check it out from here https://gethugothemes.com/products/bigspring/
