### ISSUE TITLE
Usage of hugo twitter_cards.html template overrides Twitter Card meta data in head.html

### ISSUE THREAD

**Issue by christxph** [themefisher/bigspring-light#51]
In `head.html` the `twitter:something` meta data is defined but afterwards the Hugo twitter_cards.html template is imported, which overrides whatever was set above. This can be seen in the output html, where there are multiple occurrences of e.g. the `twitter:title` or `twitter:image` tags.

Workaround:
Remove L59 in head.html

https://github.com/themefisher/bigspring-light/blob/20e45e2abbeede15e9f8eb819be5373004e17d0a/layouts/partials/head.html#L59

**Comment by somratpro** [comment]
Hello @christxph 

Thanks for your concern, this issue has been fixed. Thanks for staying with us.
