### ISSUE TITLE
Image slider dots are not centered due to user agent stylesheet

### ISSUE THREAD

**Issue by christxph** [themefisher/bigspring-light#52]
The `slick-dots` slider uses `ul` elements under the hood which have a `padding-inline-start` set by default on Chrome/Safari which means that the dots are not centered below the image. This can be fixed by adding either `padding: 0;` or `padding-inline-start: 0;` to `_main.scss` here:

https://github.com/themefisher/bigspring-light/blob/b60eba29d738767fbcf6086ffc62768c3ac5f6dd/assets/scss/templates/_main.scss#L321-L324

becomes:

```
.slick-dots {
  text-align: center;
  margin-top: 20px;
  padding-inline-start: 0;
```

**Comment by tfsomrat** [comment]
Hello @christxph 

Thanks for your concern. I fixed this issue. You can actually contribute to improving this theme. Make a PR if you found something is wrong or improve code, I'll merge it. Thank you
