### ISSUE TITLE
Can't change colors. 

### ISSUE THREAD

**Issue by atlet** [themefisher/bigspring-light#53]
I modified variables light and primary_collor in file themes/bigspring-light/config.toml but nothing has changed. Any idea what can be wrong?

**Comment by somratpro** [comment]
Hello @atlet 

I have checked this theme on my local host. but everything looks fine. please ensure that you are using hugo version 0.87.0_extended or later. and if you still have issues, please create a small video (you can use loom chrome extension) and upload it here. thank you

**Comment by atlet** [comment]
Hi @somratpro, installing Hugo extended fixed my issue. Tnx for help.
