### ISSUE TITLE
logo is broken on non-default language

### ISSUE THREAD

**Issue by ilkkapeltola** [themefisher/bigspring-light#54]
If you use the exampleSite, switch to De, you see that the logo is broken.

**Comment by tfsomrat** [comment]
Hello @ilkkapeltola 

Thank you for using our theme. We didn't provide any other language without English in the free version. Did you add a new language on your own? If you did it, make the logo URL `relURL` or `absURL`, instead of `relLangURL` or `absLangURL`.

**Comment by ilkkapeltola** [comment]
I used the exampleSite
https://github.com/themefisher/bigspring-light/tree/master/exampleSite/config/_default
it uses English and German, which when just copied to your project, is broken.
Thanks, I actually wasn't going to need other than English anyway, but just pointed it out that the setup in exampleSite seemed broken. Thanks.

**Comment by abradshaw** [comment]
Is there a fix for this?  I still have the same problem

**Comment by tfsomrat** [comment]
Hello @abradshaw ,

This issue has been fixed, re-download the latest version and try it. thank you
