### ISSUE TITLE
Adjust margins of blog posts?

### ISSUE THREAD

**Issue by eteitelbaum** [themefisher/bigspring-light#56]
Is there a way to adjust the default margins of blog posts? I have some graphs that I would like to display across most of the width of the page.

**Comment by tfsomrat** [comment]
Hey @eteitelbaum 

You can write your custom CSS here `assets/scss/_custom.scss`, it will not conflict with the main theme. And you can get your custom margin also.

**Comment by eteitelbaum** [comment]
Thanks! Can you tell me what code I need to insert to adjust the margins for the blog posts? I saw some examples online that looked like this: 

```
.content {
  max-width: [insert desired width];
} 
```

But I'm not seeing anything like that in the CSS file that I found in the `assets/scss` folder.

**Comment by tfsomrat** [comment]
I am not sure exactly where you want to increase or reduce the margin, take a screenshot and tell me in detail, then I might help you with that.

**Comment by eteitelbaum** [comment]
Thanks for your offer to help. I am attaching a .png here. Basically I want the interactive chart I have there to go most of the width of the page when you are viewing the blog post on a desktop.

![margins](https://user-images.githubusercontent.com/62634082/152243758-cdd5cb48-1be8-44ce-bd90-699d8f5721ec.png)

**Comment by tfsomrat** [comment]
Hey @eteitelbaum 
open `layouts/_default/single.html` at line 9, you will find this class `col-lg-8`, make it `col-lg-12`, it will solve your issue.
I want to let you know that, theme customization is not a free service, I hope you like our themes, please give us stars on our themes repositories, thank you.

**Comment by eteitelbaum** [comment]
Will do. Thanks.
