### ISSUE TITLE
Blog post with no picture?

### ISSUE THREAD

**Issue by eteitelbaum** [themefisher/bigspring-light#59]
Hello!

When I try to do a blog post without a picture, the theme gives me two titles (a little one and a big one). How can have the blog post with just one title? Thanks... 

![Double Title](https://user-images.githubusercontent.com/62634082/153692002-f567d195-a862-4d50-ad66-99f79bd6614d.png)

**Comment by tfsomrat** [comment]
Hello @eteitelbaum 

Thanks for your concern. I have fixed the issue, see [eda953f](https://github.com/themefisher/bigspring-light/commit/eda953f6d6439efc91b80bd57a003f680540c20e)

If you like this theme, a star to the repository would be appreciated.

**Comment by eteitelbaum** [comment]
Thank you @tfsomrat. How do I get the update to work with the site I am building? Is there a submodule I should update?

**Comment by tfsomrat** [comment]
You can simply download the theme, and replace it with your existing one. Mostly the update happened in `layouts/_default/list.html` and `layouts/_default/single.html`. If you want, you can just replace these two files only. thank you
