### ISSUE TITLE
Issue creating new normal page

### ISSUE THREAD

**Issue by chrisbrain** [themefisher/bigspring-light#61]
Hi - I am not clear how to create a new 'normal' page. The docs here:
https://docs.gethugothemes.com/guide/#maintain-page

Suggest:
`
If you want to make a copy of privacy page, then you need to duplicate 2 files. The first one is content. Duplicate the privacy page folder from the content folder with _index.md file in it. Then change the folder name to your new page name (i.e. terms-conditions). Now you have your content ready, it’s time to duplicate the structure or the markup for this new page. Go to layouts folder and also duplicate the same page folder here, in our stage, it’s privacy page. And give the same name that you give the content folder (i.e. terms-conditions). Now you have successfully duplicate a page.
`

But this theme doesn't have a privacy folder in _layouts:
https://github.com/themefisher/bigspring-light/tree/master/layouts

Also - if the above instructions were correct does this really mean you are forced to duplicate the same layout code for pages with identical layout?

Also - the bigspring docs are not much more clear IMHO:
https://docs.gethugothemes.com/bigspring/create-page/

I will likely purchase this theme if I can get a better handle on how to use it.

**Comment by mehedi-sharif** [comment]
Hello @chrisbrain 

Thanks for choosing our themes, We are sorry for this inconvenience. This theme has been updated many times, and the docs became older. we will update the docs ASAP. by the way, you can create a page in the content folder, and you don't need to create any layout. If you are looking for a privacy page, just make it like this `content/english/privacy.md`. and write your content on it. hope you understand the process.

**Comment by chrisbrain** [comment]
Thanks - yea I think I figured it out in the end, partly my limited knowledge of hugo but I think it if doesn't find a layout in the template matching the folder name then it falls back on the default ones. So you can create any folder name in the /content/english directory or just put a new .md file in the root of that directory.
