### ISSUE TITLE
gethugothemes link for download not working

### ISSUE THREAD

**Issue by Jim-Knopf** [themefisher/bigspring-light#64]
Hi everyone!
The link to download the bigspring hugo theme on gethugothemes.com is not working. It leads to a 404 page.
https://download.themefisher.com/bigspring.zip

Please have a look at this if you can!

Best,
Thomas

**Comment by tfsomrat** [comment]
Hello @Jim-Knopf ,

This is bigspring-light theme, not the bigspring theme. If you have problem with bigspring theme, you need to contact us through our support system. and if you are bigspring-light user, then you can download it from the github. thank you.
